//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndroidApplicationData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class applicationEntities : DbContext
    {
        public applicationEntities()
            : base("name=applicationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Egzersiz> Egzersiz { get; set; }
        public virtual DbSet<HbA1c> HbA1c { get; set; }
        public virtual DbSet<KanSekeri> KanSekeri { get; set; }
        public virtual DbSet<Kullanicilar> Kullanicilar { get; set; }
        public virtual DbSet<Su> Su { get; set; }
        public virtual DbSet<Tansiyon> Tansiyon { get; set; }
        public virtual DbSet<VucutKitle> VucutKitle { get; set; }
    }
}
